### ISSUE TITLE
Add git hooks to keep contributions clean?

### ISSUE THREAD

**Issue by brucellino** [jamespjh/eResearch-meeting-list#10]
I've had lots of help from [overcommit](https://github.com/sds/overcommit) to keep my commits clean. I would like to add a file `.overcommit.yml` to enable linters (essentially YAML lint for now, maybe json-schema later) to help contributors make clean contributions.

If you are open to this idea, I could send a PR.

**Comment by jamespjh** [comment]
Yes please.
