### ISSUE TITLE
Add Mozfest

### ISSUE THREAD

**Issue by jamespjh** [jamespjh/eResearch-meeting-list#21]
# Add a new event: Mozfest

Hello! I would like to add a new event.

- Name: Mozilla Festival
- Place: London
- URL: https://www.mozillafestival.org/en/

Very generic, but a lot of activity from Mozilla science on opensciency stuff so worth including.

## Checklist

- [ ] The event falls into one or more of the categories described in the README
- [x] The last instance of the event was less than 5 years ago
- [x] The event has a public website
- [ ] The event has an agenda with some form of published proceedings

## Workflow

- Associated PR: 
- [ ] Yaml file added 
  - [ ] YAML validated

**Comment by bw-faststream** [comment]
Event passed

**Comment by jamespjh** [comment]
@bw-faststream - aware it's in the past, but this is building up a list for the long term, so we know which series to keep tabs on for future instance. Include anyway.

**Comment by bw-faststream** [comment]
All add them now. For the events with multiple meetups - should I add all future events currently planned, or the nearest to the current date?

Benjamin Walden
Secondment - Civil Service Fast Stream

The Alan Turing Institute
bwalden@turing.ac.uk
07497496232

________________________________

**Comment by bw-faststream** [comment]
Planned, if time. But if not time, prioritise getting more files in over doing each one more properly.

Best,

J.

--
Dr James Hetherington FBCS

Until 31st December 2019:

Director of Research Engineering
The Alan Turing Institute

From 1st January 2020:

Director of e-Infrastructure
UK Research and Innovation


--

From: Benjamin Walden <bwalden@turing.ac.uk>
Date: Thursday, 31 October 2019 at 14:08
To: jamespjh/eResearch-meeting-list <reply@reply.github.com>, James Hetherington <jhetherington@turing.ac.uk>
Subject: Re: [jamespjh/eResearch-meeting-list] Add Mozfest (#21)

All add them now. For the events with multiple meetups - should I add all future events currently planned, or the nearest to the current date?

Benjamin Walden
Secondment - Civil Service Fast Stream

The Alan Turing Institute
bwalden@turing.ac.uk
07497496232


________________________________
