### ISSUE TITLE
Add HPC SIG

### ISSUE THREAD

**Issue by jamespjh** [jamespjh/eResearch-meeting-list#24]
# Add a new event: (Name of Event)

Hello! I would like to add a new event.

- Name: HPC-SIG
- Place: Varies
- URL: https://hpc-sig.org.uk

Organised through jiscmail at  https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=HPC-SIG

## Checklist

- [ ] The event falls into one or more of the categories described in the README
- [ ] The last instance of the event was less than 5 years ago
- [ ] The event has a public website
- [ ] The event has an agenda with some form of published proceedings

## Workflow

- Associated PR: 
- [ ] Yaml file added 
  - [ ] YAML validated

**Comment by ikirker** [comment]
(Not to be confused with ACM [SIGHPC](https://www.sighpc.org/))
