### ISSUE TITLE
update for IEEE HPEC 2020 dates

### ISSUE THREAD

**Issue by rthoelen** [jamespjh/eResearch-meeting-list#35]
# Add a new event: IEEE HPEC

Hello! I would like to add a new event.

- Name: IEEE HPEC
- Place: Waltham, MA
- URL: http://ieee-hpec.org/futuredates.htm

Submitted a pull request with the tentative dates for 2020

## Checklist

- [ X] The event falls into one or more of the categories described in the README
- [ X] The last instance of the event was less than 5 years ago
- [ X] The event has a public website
- [ X] The event has an agenda with some form of published proceedings

## Workflow

- Associated PR: 
- [ ] Yaml file added 
  - [ ] YAML validated

**Comment by jamespjh** [comment]
Thanks!
