### ISSUE TITLE
Add Tests for Events

### ISSUE THREAD

**Issue by vsoch** [jamespjh/eResearch-meeting-list#39]
hey @jamespjh ! I'd like to add tests for the events files, and the easiest way (to not need to manage credentials / connections to other services) would be to use GitHub workflows (native here). Does your username have support for them? Given that you got access, they should be free for open source, etc. (for example, usrse has them along with my username). Let me know and I'll put together a workflow!

**Comment by jamespjh** [comment]
Happy to use the GH actions/workflows beta. I've got it turned on in this account.

**Comment by jamespjh** [comment]
@vsoch added you as a collaborator to this repo.

**Comment by vsoch** [comment]
Great! I’ll put in a PR after some triage work this morning, I really like writing GH actions configs! ⛄️
