### ISSUE TITLE
File per meeting, or another format

### ISSUE THREAD

**Issue by jamespjh** [jamespjh/eResearch-meeting-list#4]
@danielskatz suggests one-file-per-meeting is annoying.

@jamespjh thinks one-file-per-meeting is better for merges.

Comments?

**Comment by danielskatz** [comment]
both are right :)

but if this sticks around, merges will get less frequent and easier over time

**Comment by ikirker** [comment]
Surely they'd get *more* frequent, since each meeting will have to have its `next` shunted to `previous` and updated, once per meeting.

**Comment by danielskatz** [comment]
But that will be spread over a full year

**Comment by ikirker** [comment]
That's fair. I'm not sure I can think of a good alternative that wouldn't become limiting later[1] and that isn't just "put bunches of stuff in arbitrary files", or "group by initial", though.

And I think small files are nicer for editing and for probably for letting people see how to do new submissions, too.

[1] For example: if you box by category, you get into some very blurry areas and you probably just want to have (multiple) tags for particular meeting interests anyway if that's a categorisation exercise you want to get into. (Non-specific you.)

**Comment by jamespjh** [comment]
Yeh, I thought about one file per category, then I decided that'd just results in disputes over categorisation and/or lack of ability to find things when you disagreed over category with the contributor. So I don't like that idea.

**Comment by jamespjh** [comment]
I think this debate is coming to an end? Unless further disputation results from this comment, will close.

**Comment by danielskatz** [comment]
fine with me - I was really thinking of https://github.com/jamespjh/eResearch-meeting-list/issues/13 when I opened this issue
