### ISSUE TITLE
Add URL to readme

### ISSUE THREAD

**Issue by danielskatz** [jamespjh/eResearch-meeting-list#44]
Currently, the README says "To add another file, simply add it to this folder in the same format, and it will render on the site." but nowhere in the README is the site itself actually listed.  I guess it's currently https://jamespjh.github.io/eResearch-meeting-list/ but I only know that from scanning other issues...

**Comment by vsoch** [comment]
I think he mentioned that he’s going to deploy it more officially elsewhere, hence why it’s missing.

**Comment by danielskatz** [comment]
@jamespjh - any news on this?  (it came up in the US-RSE slack today)

**Comment by jamespjh** [comment]
It’ll take me a while to get an official space set up for the UK e-I directorate, (workplace admin), so I guess we should just link to the current location. I’ll add this to the read email.

**Comment by vsoch** [comment]
@jamespjh if you have a domain, you can also host here (GitHub pages) but use the domain as a CNAME (it comes down to adding a CNAME here, editing the name to be in your repository settings, and then adding GitHub nameservers to your registrar).
